path: /home/hancom/miro-docker/team04/classifier_dataset
train: train/images
val: test/images
# save_dir: /home/hancom/miro-docker/team04/runs/detect/train

nc: 10

names: ["345_15","15_45","45_75","75_105","135_165","165_195","195_225","225_255","255_285","315_345"]